#!/bin/sh

. /lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	echo " Plasma Linux Live Configuration"
}

Config ()
{


	if [ ! -d /home/${LIVE_USERNAME}/Desktop ]
	then
		echo "[INFO] not found: /home/${LIVE_USERNAME}/Desktop"
		sudo -u ${LIVE_USERNAME} mkdir /home/${LIVE_USERNAME}/Desktop
	fi	
	cp /usr/share/applications/install-plasma.desktop /home/${LIVE_USERNAME}/Desktop/

	# Creating state file
	touch /var/lib/live/config/plasma-live-config
}

Cmdline
Init
Config

